### ISSUE TITLE
linkedService deletion loops endless if still used in dataset

### ISSUE THREAD

**Issue by jeroenski74** [SQLPlayer/azure.datafactory.devops#38] opened 2021-03-23 23:55 UTC
if in one iteration both the dataset that is using a linkedService and the linkedService have to be deleted (with the option to delete missing objects) first the linkedService will be deleted which results in a endless loop of removing the linkedService (see screenshot) probably because the dataset that is using the linkedService is not yet deleted. Hopefully this is solved if the order of removal is changed into dataset first and after that the linkedService:

![Endless removal of linkedService](https://user-images.githubusercontent.com/2221503/112233895-9672d800-8c3b-11eb-81a2-67d28ac8bd6a.png)

**Comment by NowinskiK** [comment] 2021-03-24 07:57
Probably, for some reason, the process can't see dependency.
Could you enable debug mode and share this part of log again?
I don't have enough information to recreate the scenario.

**Comment by jeroenski74** [comment] 2021-03-24 08:54
Hi Kamil,

I have already resolved it by first execute a release removing the datasets only.

And after that a separate release to delete the linkedService (now having 0 dependemcies)

For me it is a lot of work to reverse this again and I'm having some time pressure on the project so I'm not able to reproduce the debug logging any time soon.

The case to reproduce should be:

Create a linkedService
Create a dataset on it
Deploy
Delete both in the same release
Deploy again

And the looping should happen

If I find some time I will try to do the above in a separate environment (my own)!

With kind regards,
Jeroen

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden

________________________________
Van: Kamil Nowinski ***@***.***>
Verstuurd: woensdag 24 maart 2021 08:57
Aan: SQLPlayer/azure.datafactory.devops
Cc: jeroenski74; Author
Onderwerp: Re: [SQLPlayer/azure.datafactory.devops] linkedService deletion loops endless if still used in dataset (#38)


Probably, for some reason, the process can't see dependency.
Could you enable debug mode and share this part of log again?
I don't have enough information to recreate the scenario.

**Comment by Joehannus** [comment] 2021-04-23 12:02
I have the same issue when trying to delete a Dataset :-(

**Comment by NowinskiK** [comment] 2021-04-23 13:58
@Joehannus , can you share your log and (more important) file of that Dataset?

**Comment by NowinskiK** [comment] 2021-04-27 14:29
I reproduced the steps you provided and can't reproduce the issue. 
```powershell
git clone https://github.com/SQLPlayer/azure.datafactory.examples.git

Install-Module 'azure.datafactory.tools' -MinimumVersion '0.61'
Import-Module 'az.datafactory' 
Get-Module 'az*'

$rg = 'kamilnow-rg1'
$adf = 'adf-simpledeployment-2021'
$folder = ".\azure.datafactory.examples\adf-simpledeployment"

Publish-AdfV2FromJson -RootFolder $folder -ResourceGroupName $rg -DataFactoryName $adf -Location 'uksouth'

Remove-Item -Path ".\azure.datafactory.examples\adf-simpledeployment\dataset\*.*"
Remove-Item -Path ".\azure.datafactory.examples\adf-simpledeployment\pipeline\*.*"

$o = New-AdfPublishOption 
$o.DeleteNotInSource = $true
Publish-AdfV2FromJson -RootFolder $folder -ResourceGroupName $rg -DataFactoryName $adf -Option $o
```

I'm closing the task, but feel free to open this up once you can provide the steps to reproduce the error. Thx.

**Closed by NowinskiK** 2021-04-27 14:29 UTC
Labels: triage
